# Generated by Django 2.1.2 on 2018-11-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='strava_id',
        ),
        migrations.AddField(
            model_name='activities',
            name='athlete',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Athlete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_logon_date',
            field=models.DateTimeField(verbose_name='last logon'),
        ),
    ]
